-- This module is minimal and contains only the weight values
-- so that it can be easily generated by tuning software

module Struct.Weights (
    weights,
) where

import Struct.ParamsPre

-- The configurable weights we use
-- Every weight has two values, one for mid game, one for end game
-- The format is: (paramName, (defaultValueMid, defaultValueEnd))
-- All weights have type MidEnd
weights :: [EvalWeightSpec]
weights = [
        ("ewMaterialDiff",    (   8,    8)),
        ("ewKingSafe",        (   1,    0)),
        ("ewKingOpen",        (   2,    4)),
        ("ewKingPlaceCent",   (   8,    1)),
        ("ewKingPlacePwns",   (   0,    4)),
        ("ewKingPawn",        (   3,   50)),
        ("ewKingThreat",      (   0,  300)),
        ("ewKingProtB",       (  -8,  -12)),	-- king protect bishop
        ("ewKingProtN",       ( -16,  -28)),	-- king protect knight
        ("ewRookHOpen",       ( 183,  180)),	-- Open & semiopen together
        ("ewRookConn",        (  98,    1)),
        ("ewRookKingFile",    (  96,    0)),	-- inspired by Stockfish 13
        ("ewRookKingRank",    ( 160,  140)),	-- guessed
        ("ewMobilityKnight",  (  70,   54)),	-- texel2 / o: 62, 47
        ("ewMobilityBishop",  (  67,   32)),	-- texel2 / o: 61, 29
        ("ewMobilityRook",    (  32,   40)),	-- texel2 / o: 32, 39
        ("ewMobilityQueen",   (   4,   22)),	-- texel2 / o:  4, 22
        ("ewCenterPAtts",     (  73,   57)),
        ("ewCenterNAtts",     (  33,    0)),
        ("ewCenterBAtts",     (  98,    0)),	-- inspired by Stockfish 13
        ("ewCenterRAtts",     (  14,   22)),	-- DSPSA ...
        ("ewCenterQAtts",     (  13,   53)),
        ("ewCenterKAtts",     (   0,   40)),
        ("ewCenterNOcc",      ( 130,    0)),
        ("ewSpace",           (   1,    0)),
        ("ewAdvAtts",         (   0,   12)),
        ("ewWeakSq",          ( -32,    0)),
        ("ewWeakSqA",         ( 100,    0)),
        ("ewIsolPawns",       ( -36, -113)),
        ("ewIsolPassed",      ( -63, -143)),
        ("ewBackPawns",       (-108, -141)),
        ("ewBackPOpen",       ( -21,  -27)),
        ("ewEnpHanging",      ( -19,  -27)),
        ("ewEnpEnPrise",      ( -29,  -26)),
        ("ewEnpAttacked",     (  -2,  -14)),
        ("ewWepTotal",        ( 150,    0)),
        ("ewWepAttacked",     (   0,  200)),
        ("ewBishopPair",      ( 386,  323)),
        ("ewBishopPawns",     ( -25,  -54)),
        ("ewRookPawn",        ( -44,  -32)),
        ("ewAdvPawn5",        (  14,  106)),
        ("ewAdvPawn6",        ( 352,  333)),
        ("ewPawnBlockP",      (-112,  -92)),
        ("ewPawnBlockO",      ( -23,  -26)),
        ("ewPawnBlockA",      ( -19,  -69)),
        ("ewPassPawnLev",     (   2,    8))
    ]
