#!/usr/bin/env python3
"""Generate Struct.Weights from a config file with mid./end. assignments."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class WeightPair:
    name: str
    mid: int | None = None
    end: int | None = None


COMMENT_RE = re.compile(r"^\s*(?:--.*)?$")


def parse_value(raw: str, line_no: int) -> int:
    text = "".join(raw.split())
    try:
        return int(round(float(text)))
    except ValueError as exc:
        raise ValueError(f"line {line_no}: cannot parse '{raw.strip()}' as a number") from exc


def parse_config(path: Path) -> list[WeightPair]:
    weights: dict[str, WeightPair] = {}
    order: list[str] = []

    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if COMMENT_RE.match(line):
            continue
        if "=" not in line:
            raise ValueError(f"line {line_no}: line does not contain '='")
        lhs, rhs = line.split("=", 1)
        key = "".join(lhs.split())
        if "." not in key:
            raise ValueError(f"line {line_no}: parameter '{key}' must use mid./end. prefix")
        phase, name = key.split(".", 1)
        if phase not in {"mid", "end"} or not name:
            raise ValueError(f"line {line_no}: invalid parameter name '{key}'")

        pair = weights.get(name)
        if pair is None:
            pair = WeightPair(name=name)
            weights[name] = pair
            order.append(name)

        value = parse_value(rhs, line_no)
        if phase == "mid":
            if pair.mid is not None:
                raise ValueError(f"line {line_no}: duplicate mid value for '{name}'")
            pair.mid = value
        else:
            if pair.end is not None:
                raise ValueError(f"line {line_no}: duplicate end value for '{name}'")
            pair.end = value

    result = [weights[name] for name in order]
    for pair in result:
        if pair.mid is None or pair.end is None:
            raise ValueError(f"incomplete weight '{pair.name}': both mid and end values are required")
    return result


def render_module(weights: list[WeightPair], source_path: Path) -> str:
    lines = [
        "-- This module is minimal and contains only the weight values",
        "-- so that it can be easily generated by tuning software",
        f"-- Generated from config file: {source_path.as_posix()}",
        "",
        "module Struct.Weights (",
        "    weights,",
        ") where",
        "",
        "import Struct.ParamsPre",
        "",
        "-- The configurable weights we use",
        "-- Every weight has two values, one for mid game, one for end game",
        "-- The format is: (paramName, (defaultValueMid, defaultValueEnd))",
        "-- All weights have type MidEnd",
        "weights :: [EvalWeightSpec]",
        "weights = [",
    ]

    if weights:
        name_width = max(len(pair.name) for pair in weights)
        mid_width = max(len(str(pair.mid)) for pair in weights)
        end_width = max(len(str(pair.end)) for pair in weights)
        for index, pair in enumerate(weights):
            prefix = "        " if index == 0 else "      , "
            name_field = f"\"{pair.name}\"".ljust(name_width + 2)
            mid_field = str(pair.mid).rjust(mid_width)
            end_field = str(pair.end).rjust(end_width)
            lines.append(f"{prefix}({name_field}, ({mid_field}, {end_field}))")
    lines.append("    ]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert a mid./end. config file into Struct/Weights.hs."
    )
    parser.add_argument("input", type=Path, help="Input config file")
    parser.add_argument("output", type=Path, help="Output Haskell module path")
    args = parser.parse_args()

    weights = parse_config(args.input)
    module_text = render_module(weights, args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(module_text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # pragma: no cover
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
